
export const mockProfiles = [
  {
    id: "profile-1",
    userId: "user-1",
    name: "Maria Silva",
    photoUrl: "https://i.pravatar.cc/150?img=1",
    tokensBalance: 100,
    learningLang: "en",
    learningLevel: "B1",
    knownLanguages: ["pt", "es"],
    chatIds: [],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    user: {
      email: "maria.silva@example.com",
    },
  },
  {
    id: "profile-2",
    userId: "user-2",
    name: "John Smith",
    photoUrl: "https://i.pravatar.cc/150?img=2",
    tokensBalance: 150,
    learningLang: "pt",
    learningLevel: "A2",
    knownLanguages: ["en", "es"],
    chatIds: [],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    user: {
      email: "john.smith@example.com",
    },
  },
  {
    id: "profile-3",
    userId: "user-3",
    name: "Ana Costa",
    photoUrl: "https://i.pravatar.cc/150?img=3",
    tokensBalance: 80,
    learningLang: "fr",
    learningLevel: "C1",
    knownLanguages: ["pt"],
    chatIds: [],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    user: {
      email: "ana.costa@example.com",
    },
  },
  {
    id: "profile-4",
    userId: "user-4",
    name: "Carlos Rodriguez",
    photoUrl: "https://i.pravatar.cc/150?img=4",
    tokensBalance: 200,
    learningLang: "en",
    learningLevel: "B2",
    knownLanguages: ["es", "pt"],
    chatIds: [],
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
    user: {
      email: "carlos.rodriguez@example.com",
    },
  },
  {
    id: "profile-5",
    userId: "user-5",
    name: "Sophie Dubois",
    photoUrl: "https://i.pravatar.cc/150?img=5",
    tokensBalance: 120,
    learningLang: "en",
    learningLevel: "A1",
    knownLanguages: ["fr"],
    chatIds: [],
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
    user: {
      email: "sophie.dubois@example.com",
    },
  },
];

export const mockMessages = [
  {
    id: "msg-1",
    content: "Hey! How are you doing today?",
    senderId: "user-2",
    chatId: "chat-1",
    translation: null,
    correctionSuggestions: null,
    createdAt: new Date(Date.now() - 3600000),
    updatedAt: new Date(Date.now() - 3600000),
    sender: {
      id: "user-2",
      name: "John Smith",
      photoUrl: "https://i.pravatar.cc/150?img=2",
    },
  },
  {
    id: "msg-2",
    content: "Olá! Estou bem, obrigado. E você?",
    senderId: "user-1",
    chatId: "chat-1",
    translation: null,
    correctionSuggestions: null,
    createdAt: new Date(Date.now() - 3500000),
    updatedAt: new Date(Date.now() - 3500000),
    sender: {
      id: "user-1",
      name: "Maria Silva",
      photoUrl: "https://i.pravatar.cc/150?img=1",
    },
  },
  {
    id: "msg-3",
    content: "I'm doing great! Are you practicing your English today?",
    senderId: "user-2",
    chatId: "chat-1",
    translation: null,
    correctionSuggestions: null,
    createdAt: new Date(Date.now() - 3000000),
    updatedAt: new Date(Date.now() - 3000000),
    sender: {
      id: "user-2",
      name: "John Smith",
      photoUrl: "https://i.pravatar.cc/150?img=2",
    },
  },
  {
    id: "msg-4",
    content: "Yes! I trying to improve my vocabulary every day.",
    senderId: "user-1",
    chatId: "chat-1",
    translation: null,
    correctionSuggestions: {
      suggestion: "Yes! I'm trying to improve my vocabulary every day.",
      explanation: 'Use "I\'m trying" instead of "I trying" - present continuous requires the verb "to be".',
    },
    createdAt: new Date(Date.now() - 2500000),
    updatedAt: new Date(Date.now() - 2500000),
    sender: {
      id: "user-1",
      name: "Maria Silva",
      photoUrl: "https://i.pravatar.cc/150?img=1",
    },
  },
  {
    id: "msg-5",
    content: "That's wonderful! Keep up the good work! 🎉",
    senderId: "user-2",
    chatId: "chat-1",
    translation: null,
    correctionSuggestions: null,
    createdAt: new Date(Date.now() - 2000000),
    updatedAt: new Date(Date.now() - 2000000),
    sender: {
      id: "user-2",
      name: "John Smith",
      photoUrl: "https://i.pravatar.cc/150?img=2",
    },
  },
];

export const mockChats = [
  {
    id: "chat-1",
    name: null,
    isGroup: false,
    participantIds: ["user-1", "user-2"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date(Date.now() - 2000000),
    participants: [
      {
        id: "user-2",
        name: "John Smith",
        photoUrl: "https://i.pravatar.cc/150?img=2",
      },
    ],
    lastMessage: {
      id: "msg-5",
      content: "That's wonderful! Keep up the good work! 🎉",
      senderId: "user-2",
      createdAt: new Date(Date.now() - 2000000),
    },
  },
];
